//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlowlernerDbEntities : DbContext
    {
        public SlowlernerDbEntities()
            : base("name=SlowlernerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointment { get; set; }
        public virtual DbSet<collection> collection { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<patientPractic> patientPractic { get; set; }
        public virtual DbSet<PatientTest> PatientTest { get; set; }
        public virtual DbSet<PatientTestCollectionFeedback> PatientTestCollectionFeedback { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<PersonIdentification> PersonIdentification { get; set; }
        public virtual DbSet<PersonIdentificationFeedback> PersonIdentificationFeedback { get; set; }
        public virtual DbSet<PersonPicture> PersonPicture { get; set; }
        public virtual DbSet<PersonPractice> PersonPractice { get; set; }
        public virtual DbSet<PersonTest> PersonTest { get; set; }
        public virtual DbSet<PersonTestCollection> PersonTestCollection { get; set; }
        public virtual DbSet<Practic> Practic { get; set; }
        public virtual DbSet<practicCollection> practicCollection { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<testCollection> testCollection { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
