//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPicture
    {
        public int personpictureid { get; set; }
        public string imgPath { get; set; }
        public Nullable<int> personid { get; set; }
    
        public virtual person person { get; set; }
    }
}
