//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPractice
    {
        public int personPractice1 { get; set; }
        public Nullable<int> personId { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> created_by { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual person person { get; set; }
        public virtual User User { get; set; }
    }
}
