//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonIdentificationFeedback
    {
        public int pifId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> personTestId { get; set; }
        public Nullable<int> personId { get; set; }
        public Nullable<bool> feedback { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual person person { get; set; }
        public virtual PersonTest PersonTest { get; set; }
    }
}
