//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class practicCollection
    {
        public int prac_collect_Id { get; set; }
        public int collectId { get; set; }
        public int pracId { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual Practic Practic { get; set; }
    }
}
