//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testCollection
    {
        public int test_collect_Id { get; set; }
        public int collectId { get; set; }
        public int testId { get; set; }
        public Nullable<int> op1 { get; set; }
        public Nullable<int> op2 { get; set; }
        public Nullable<int> op3 { get; set; }
    
        public virtual collection collection { get; set; }
        public virtual collection collection1 { get; set; }
        public virtual collection collection2 { get; set; }
        public virtual collection collection3 { get; set; }
        public virtual Test Test { get; set; }
    }
}
